export {
  type CommandScope,
  COMMAND_SCOPE_ORDER,
  DEFAULT_SCOPE,
  type Option,
  OptionSchema,
  type Command,
  CommandSchema,
  type CommandHandler,
  type CommandContext,
  type StorageContext,
  type OutputContext,
  type OutputMode,
  type SiteConfig,
  type ZodSchema,
  type XCLIAPI,
  type CommandEntry,
  type SiteInstance,
  type FlagConfig,
  type ToolConfig,
  type EventHandler,
  type EventContext,
  CommandError,
  SiteInstanceImpl,
  buildInputSchema,
  validateArgs,
} from './plugin-protocol.js';
